services:
  - type: web
    name: codeboost
    env: node
    plan: free
    buildCommand: node render-build.js
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: "*"
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
    healthCheckPath: /health-check
    nodeVersion: 18.17.0