services:
  - type: web
    name: codeboost
    env: node
    plan: free
    buildCommand: |
      # Print Node.js version for debugging
      echo "Using Node.js $(node --version)"
      
      # Install dependencies
      npm install
      
      # Install client dependencies and build
      cd client
      npm install
      
      # Fix potential crypto issues with Vite
      export NODE_OPTIONS="--no-experimental-fetch --openssl-legacy-provider"
      
      npm run build
      cd ..
      
      # Install server dependencies
      cd server
      npm install
      
      # Create public directory in server
      mkdir -p public
      
      # Copy client build to server/public
      cp -r ../client/dist/* public/
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: "*"
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
    healthCheckPath: /
    nodeVersion: 18.17.0