services:
  - type: web
    name: codeboost
    env: node
    plan: free
    buildCommand: |
      echo "=========== STARTING BUILD PROCESS ==========="
      
      # Install dependencies
      npm install
      
      # Install client dependencies 
      cd client
      npm install
      
      # Fix Vite build issues
      export NODE_OPTIONS="--no-experimental-fetch --openssl-legacy-provider"
      
      # Attempt to build client
      echo "Building client..."
      npm run build || echo "Client build failed, will use fallback"
      
      # Go back to root
      cd ..
      
      # Set up server 
      cd server
      npm install
      
      # Create public directory and index.html directly
      echo "Creating public directory and index.html..."
      mkdir -p public
      
      # Create a guaranteed working index.html file
      cat > public/index.html << 'EOF'
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CodeBoost - Online Code Editor</title>
        <style>
          body { font-family: system-ui, sans-serif; margin: 0; padding: 0; background-color: #88BDBC; color: #112D32; }
          #app { display: flex; flex-direction: column; min-height: 100vh; }
          header { background-color: #254E58; color: white; padding: 1rem; }
          .logo { font-weight: bold; font-size: 2rem; }
          main { flex: 1; padding: 2rem; max-width: 800px; margin: 0 auto; width: 100%; }
          .card { background-color: white; border-radius: 8px; padding: 2rem; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }
          .btn { background-color: #254E58; color: white; border: none; padding: 10px 20px; border-radius: 4px; cursor: pointer; font-weight: bold; margin: 5px; }
          .btn:hover { background-color: #112D32; }
          footer { background-color: #254E58; color: white; padding: 1rem; text-align: center; }
          .center { text-align: center; }
        </style>
      </head>
      <body>
        <div id="app">
          <header>
            <div class="logo">CodeBoost</div>
          </header>
          <main>
            <div class="card">
              <h1>Welcome to CodeBoost</h1>
              <p>An online code editor and execution platform where you can write, run, and share code.</p>
              <div class="center">
                <a href="/api/users/test"><button class="btn">Test API</button></a>
                <a href="/debug-paths"><button class="btn">Debug Info</button></a>
                <a href="/login"><button class="btn">Login</button></a>
                <a href="/register"><button class="btn">Register</button></a>
              </div>
            </div>
          </main>
          <footer>
            &copy; 2023 CodeBoost
          </footer>
        </div>
      </body>
      </html>
      EOF
      
      # Copy other client files if they exist
      if [ -d "../client/dist" ]; then
        cp -r ../client/dist/* public/ || echo "Copy failed, using fallback files only"
      fi
      
      # Create a .env file with the correct configurations
      echo "Creating production .env file"
      cat > .env << EOF
      MONGODB_URI="${MONGODB_URI}"
      JWT_SECRET="${JWT_SECRET}"
      PORT=10000
      CLIENT_URL="*"
      JUDGE0_API_URL="${JUDGE0_API_URL}"
      JUDGE0_API_KEY="${JUDGE0_API_KEY}"
      EOF
      
      echo "Build process completed!"
    startCommand: cd server && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: "*"
      - key: JUDGE0_API_URL
        sync: false
      - key: JUDGE0_API_KEY
        sync: false
    healthCheckPath: /
    nodeVersion: 18.17.0